services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: 123456aA_!
      ACCEPT_EULA: Y
      MSSQL_DBNAME: N5ChallengeDb
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - backend

  api:
    build:
      context: ./N5Challenge.Api
      dockerfile: Dockerfile
    container_name: n5challenge-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=N5ChallengeDb;User=sa;Password=123456aA_!;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - backend

volumes:
  sqlserverdata:

networks:
  backend:
