// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using N5Challenge.Api.Infraestructure.SQL;

#nullable disable

namespace N5Challenge.Api.Infraestructure.SQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250611035413_migracion1234")]
    partial class migracion1234
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("N5Challenge.Api.Infraestructure.Entities.PermissionDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionTypeId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeFirstName = "Adam",
                            EmployeeLastName = "Tolosa",
                            PermissionTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeFirstName = "Tolosa",
                            EmployeeLastName = "Adam",
                            PermissionTypeId = 2
                        });
                });

            modelBuilder.Entity("N5Challenge.Api.Infraestructure.Entities.PermissionTypeDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Permiso 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Permiso 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Permiso 3"
                        });
                });

            modelBuilder.Entity("N5Challenge.Api.Infraestructure.Entities.PermissionDB", b =>
                {
                    b.HasOne("N5Challenge.Api.Infraestructure.Entities.PermissionTypeDB", "Type")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("N5Challenge.Api.Infraestructure.Entities.PermissionTypeDB", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
